<?php $objm = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php $customerSession = $objm->get('Magento\Customer\Model\Session'); ?>
<fieldset class="fieldset info">
?>">
    <div class="field required">
        <label class="label" for="facebook"><span><?= $block->escapeHtml(__('Facebook')) ?></span></label>
        <div class="control">
            <input type="text" value="<?php echo $customerSession->getCustomer()->getFacebook();?>" name="facebook" id="facebook" data-input="facebook" class="input-text" data-validate="{required:true}" /><br>
        </div>
        <br>
        <label class="label" for="job"><span><?= $block->escapeHtml(__('Job')) ?></span></label>
        <div class="control">
            <input type="text" value="<?php echo $customerSession->getCustomer()->getJob();?>" name="job" id="job" data-input="job" class="input-text"  data-validate="{required:true}" /><br>
        </div><br>
        <label class="label" for="bio"><span><?= $block->escapeHtml(__('Bio')) ?></span></label>
        <div class="control">
            <input type="text" value="<?php echo $customerSession->getCustomer()->getBio();?>" name="bio" id="bio" data-input="bio" class="input-text"
               data-validate="{required:true}" />
        </div><br>
        <label class="label" for="twitter"><span><?= $block->escapeHtml(__('Twitter')) ?></span></label>
        <div class ="control">
            <input type="text" value="<?php echo $customerSession->getCustomer()->getTwitter();?>" name="twitter" id="twitter" data-input="twitter" class="input-text"
               data-validate="{required:true}" />
        </div><br>
        <label class="label" for="avatar"><span><?= $block->escapeHtml(__('avatar')) ?></span></label>
        <div class="control">
            <input type="text" value="<?php echo $customerSession->getCustomer()->getavatar();?>" name="avatar" id="avatar" data-input="avatar" class="input-text"
               data-validate="{required:true}" />
        </div><br>
        <label class="label" for="avatar"><span><?= $block->escapeHtml(__('Customer_Id')) ?></span></label>
            <input type="text" value="<?php echo $customerSession->getCustomer()->getavatar();?>" name="customer_id" id="customer_id" data-input="customer_id" class="input-text"
               data-validate="{required:true}" />
    </div>
</fieldset>